title: Owen English # your name (or website title) here
description: > 
  Finance student at Lehigh University.  
  <br>
  Passionate about analytics, trading, and financial markets.  
  <br>
  Check out my portfolio and projects below.
  <br>
  <a href="https://www.linkedin.com/in/owen-english4/">LinkedIn</a> 
  <br>
  <a href="https://www.GitHub.com/OwenEnglish4/">GitHub</a>  
  <br>

theme: jekyll-theme-minimal
